/* 
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

namespace CherwellConnector.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    using System.Text;

    using Newtonsoft.Json;

    /// <summary>
    /// TrebuchetWebApiDataContractsCoreSimplePromptValue
    /// </summary>
    [DataContract]
    public partial class TrebuchetWebApiDataContractsCoreSimplePromptValue :  IEquatable<TrebuchetWebApiDataContractsCoreSimplePromptValue>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrebuchetWebApiDataContractsCoreSimplePromptValue" /> class.
        /// </summary>
        /// <param name="promptDefId">promptDefId.</param>
        /// <param name="promptName">promptName.</param>
        /// <param name="value">value.</param>
        public TrebuchetWebApiDataContractsCoreSimplePromptValue(string promptDefId = default(string), string promptName = default(string), string value = default(string))
        {
            this.PromptDefId = promptDefId;
            this.PromptName = promptName;
            this.Value = value;
        }
        
        /// <summary>
        /// Gets or Sets PromptDefId
        /// </summary>
        [DataMember(Name="promptDefId", EmitDefaultValue=false)]
        public string PromptDefId { get; set; }

        /// <summary>
        /// Gets or Sets PromptName
        /// </summary>
        [DataMember(Name="promptName", EmitDefaultValue=false)]
        public string PromptName { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TrebuchetWebApiDataContractsCoreSimplePromptValue {\n");
            sb.Append("  PromptDefId: ").Append(this.PromptDefId).Append("\n");
            sb.Append("  PromptName: ").Append(this.PromptName).Append("\n");
            sb.Append("  Value: ").Append(this.Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TrebuchetWebApiDataContractsCoreSimplePromptValue);
        }

        /// <summary>
        /// Returns true if TrebuchetWebApiDataContractsCoreSimplePromptValue instances are equal
        /// </summary>
        /// <param name="input">Instance of TrebuchetWebApiDataContractsCoreSimplePromptValue to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TrebuchetWebApiDataContractsCoreSimplePromptValue input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PromptDefId == input.PromptDefId ||
                    (this.PromptDefId != null &&
                    this.PromptDefId.Equals(input.PromptDefId))
                ) && 
                (
                    this.PromptName == input.PromptName ||
                    (this.PromptName != null &&
                    this.PromptName.Equals(input.PromptName))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PromptDefId != null)
                    hashCode = hashCode * 59 + this.PromptDefId.GetHashCode();
                if (this.PromptName != null)
                    hashCode = hashCode * 59 + this.PromptName.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
